# Generated by Django 2.2 on 2019-08-19 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_path', models.TextField()),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('post_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
