# Generated by Django 2.2 on 2019-08-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_path',
            new_name='article_uuid',
        ),
    ]
