# Generated by Django 2.2 on 2019-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190819_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_uuid',
            field=models.TextField(null=True),
        ),
    ]
